# Generated by Django 4.2.9 on 2024-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="leave_type",
            field=models.CharField(
                blank=True,
                choices=[("half_day", "Half Day"), ("full_day", "Full Day")],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("present", "Present"), ("leave", "Leave")], max_length=20
            ),
        ),
    ]
